name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
      - master
  # Replace pull_request with pull_request_target if you
  # plan to use this action with forks, see the Limitations section
  pull_request:
    branches:
      - main

# Down scope as necessary via https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
permissions:
  checks: write
  contents: write

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      # Install your linters here

      - name: Run linters
        uses: wearerequired/lint-action@v2

        # Enable your linters here


  run-unit-tests:
    name: Run Unit Tests
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
  run-instrumentation-tests:
    name: Run Instrumentation (UI) Tests
    runs-on: macos-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
      - name: Start Android Emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: arm64
          profile: pixel_5
          script: ./gradlew connectedDebugAndroidTest
